/-
What the exposure filtration of `lem:exposure` determines.

`expFiltration d k` is generated by the configuration together with the events
`{U_k(y) ≥ j+1, ρ_j(y) = x}`, so it records the configuration and the
instructions of index below the odometer after `k` rounds.  Three things
follow, and they are what the rest of Section 5 uses.

- The odometer after `k` rounds is itself `G_k`-measurable: `{U_k(y) ≥ j+1}`
  is the countable union over `x` of the generators.
- So is the arrival count `I_{y,x}(U_k(y))`, because on `{U_k(y) = M}` it is
  the finite sum of the generators of index below `M`.
- Hence the field `η + ∑_y I_{y,x}(U_k(·))`, whose positive part is the
  odometer of the closed recursion `eq:parallel`, is `G_k`-measurable, and it
  agrees almost surely with `U_{k+1}`.

The last statement is almost sure and not pathwise; see the shift record for
why no pathwise statement about `U_{k+1}` is available.  A particle standing at
a site it is not a candidate for reads the instruction of index exactly
`U_{t+1}(y)`, which no generator records, and its later position depends on
that instruction.  Under the law the instructions are neighbours of their site,
which is what forbids that, so the two odometers agree almost surely.
-/
import Parking.Support.Filtration
import Parking.Support.Measurability
import Parking.Support.Comparison
import Parking.Support.Parallel
import Parking.Support.ActivityHoles

open MeasureTheory

noncomputable section

namespace Parking

open LatticeProb Finset

variable {d : ℕ}

/-! ### The filtration is a filtration -/

theorem expFiltration_le (d : ℕ) : ∀ k : ℕ,
    expFiltration d k ≤ inferInstanceAs (MeasurableSpace (Data d))
  | 0 => by
      refine MeasurableSpace.comap_le_iff_le_map.mpr ?_
      exact fun s hs => measurable_fst hs
  | k + 1 => by
      refine sup_le (expFiltration_le d k) ?_
      refine MeasurableSpace.generateFrom_le ?_
      rintro A ⟨y, j, x, rfl⟩
      exact measurableSet_U_ge_and (k + 1) y x j

theorem expFiltration_mono (d : ℕ) : Monotone (expFiltration d) := by
  refine monotone_nat_of_le_succ fun k => ?_
  exact le_sup_left

theorem measurable_eta_expFiltration (k : ℕ) (x : Site d) :
    Measurable[expFiltration d k] fun ω : Data d => ω.1 x := by
  have hcomap : Measurable[expFiltration d 0] (fun ω : Data d => ω.1) :=
    measurable_iff_comap_le.mpr le_rfl
  have h0 : Measurable[expFiltration d 0] fun ω : Data d => ω.1 x :=
    (measurable_pi_apply x).comp hcomap
  exact h0.mono (expFiltration_mono d (Nat.zero_le k)) le_rfl

/-! ### The generators, and the odometer they determine -/

theorem measurableSet_generator (k : ℕ) (y x : Site d) (j : ℕ) :
    MeasurableSet[expFiltration d (k + 1)]
      {ω : Data d | j + 1 ≤ U ω (k + 1) y ∧ ω.2.1 (y, j) = x} := by
  have h1 : MeasurableSet[MeasurableSpace.generateFrom
      {A : Set (Data d) | ∃ (y : Site d) (j : ℕ) (x : Site d),
        A = {ω : Data d | j + 1 ≤ U ω (k + 1) y ∧ ω.2.1 (y, j) = x}}]
      {ω : Data d | j + 1 ≤ U ω (k + 1) y ∧ ω.2.1 (y, j) = x} :=
    MeasurableSpace.measurableSet_generateFrom ⟨y, j, x, rfl⟩
  exact (le_sup_right : MeasurableSpace.generateFrom
      {A : Set (Data d) | ∃ (y : Site d) (j : ℕ) (x : Site d),
        A = {ω : Data d | j + 1 ≤ U ω (k + 1) y ∧ ω.2.1 (y, j) = x}}
      ≤ expFiltration d (k + 1)) _ h1

theorem measurableSet_U_ge_expFiltration (k : ℕ) (y : Site d) (j : ℕ) :
    MeasurableSet[expFiltration d k] {ω : Data d | j + 1 ≤ U ω k y} := by
  cases k with
  | zero =>
      have hempty : {ω : Data d | j + 1 ≤ U ω 0 y} = ∅ := by
        ext ω
        simp only [Set.mem_setOf_eq, Set.mem_empty_iff_false, iff_false]
        have : U ω 0 y = 0 := rfl
        omega
      rw [hempty]
      exact @MeasurableSet.empty _ (expFiltration d 0)
  | succ k =>
      have hunion : {ω : Data d | j + 1 ≤ U ω (k + 1) y}
          = ⋃ x : Site d, {ω : Data d | j + 1 ≤ U ω (k + 1) y ∧ ω.2.1 (y, j) = x} := by
        ext ω
        simp only [Set.mem_setOf_eq, Set.mem_iUnion]
        constructor
        · intro h
          exact ⟨ω.2.1 (y, j), h, rfl⟩
        · rintro ⟨x, h, -⟩
          exact h
      rw [hunion]
      exact @MeasurableSet.iUnion _ _ (expFiltration d (k + 1)) _ _
        fun x => measurableSet_generator k y x j

theorem measurable_U_expFiltration (k : ℕ) (y : Site d) :
    Measurable[expFiltration d k] fun ω : Data d => U ω k y := by
  refine @measurable_to_countable' ℕ (Data d) _ _ (expFiltration d k) _ fun v => ?_
  have hsplit : (fun ω : Data d => U ω k y) ⁻¹' {v}
      = {ω : Data d | v ≤ U ω k y} \ {ω : Data d | v + 1 ≤ U ω k y} := by
    ext ω
    simp only [Set.mem_preimage, Set.mem_singleton_iff, Set.mem_sdiff, Set.mem_setOf_eq]
    omega
  rw [hsplit]
  refine @MeasurableSet.diff _ (expFiltration d k) _ _ ?_ (measurableSet_U_ge_expFiltration k y v)
  cases v with
  | zero =>
      have : {ω : Data d | 0 ≤ U ω k y} = Set.univ := by
        ext ω
        simp
      rw [this]
      exact @MeasurableSet.univ _ (expFiltration d k)
  | succ v => exact measurableSet_U_ge_expFiltration k y v

theorem measurableSet_U_le_expFiltration (k : ℕ) (y : Site d) (j : ℕ) :
    MeasurableSet[expFiltration d k] {ω : Data d | U ω k y ≤ j} := by
  have hcompl : {ω : Data d | U ω k y ≤ j} = {ω : Data d | j + 1 ≤ U ω k y}ᶜ := by
    ext ω
    simp only [Set.mem_setOf_eq, Set.mem_compl_iff]
    omega
  rw [hcompl]
  exact @MeasurableSet.compl _ _ (expFiltration d k) (measurableSet_U_ge_expFiltration k y j)

/-! ### The arrivals read in the first `k` rounds -/

theorem measurable_arrivals_expFiltration (k : ℕ) (y x : Site d) :
    Measurable[expFiltration d k] fun ω : Data d => arrivals ω.2.1 y x (U ω k y) := by
  classical
  refine @measurable_of_countable_partition (Data d) ℕ ℕ (expFiltration d k) _ _ _ _
    (fun ω => U ω k y) (measurable_U_expFiltration k y)
    (fun ω => arrivals ω.2.1 y x (U ω k y))
    (fun M ω => ((Finset.range M).filter
      fun j => j + 1 ≤ U ω k y ∧ ω.2.1 (y, j) = x).card) ?_ ?_
  · intro M
    refine @measurable_to_countable' ℕ (Data d) _ _ (expFiltration d k) _ fun v => ?_
    have : ((fun ω : Data d => ((Finset.range M).filter
        fun j => j + 1 ≤ U ω k y ∧ ω.2.1 (y, j) = x).card) ⁻¹' {v})
        = ⋃ s ∈ (Finset.range M).powerset.filter (fun s => s.card = v),
            ((⋂ j ∈ s, {ω : Data d | j + 1 ≤ U ω k y ∧ ω.2.1 (y, j) = x}) ∩
              ⋂ j ∈ (Finset.range M) \ s, {ω : Data d | j + 1 ≤ U ω k y ∧
                ω.2.1 (y, j) = x}ᶜ) := by
      ext ω
      simp only [Set.mem_preimage, Set.mem_singleton_iff, Set.mem_iUnion, Set.mem_inter_iff,
        Set.mem_iInter, Set.mem_setOf_eq, Set.mem_compl_iff, Finset.mem_filter,
        Finset.mem_powerset, exists_prop]
      constructor
      · intro h
        refine ⟨(Finset.range M).filter fun j => j + 1 ≤ U ω k y ∧ ω.2.1 (y, j) = x,
          ⟨Finset.filter_subset _ _, h⟩, ?_, ?_⟩
        · intro j hj
          exact (Finset.mem_filter.mp hj).2
        · intro j hj
          rw [Finset.mem_sdiff, Finset.mem_filter] at hj
          intro hc
          exact hj.2 ⟨hj.1, hc⟩
      · rintro ⟨s, ⟨hsub, hcard⟩, hin, hout⟩
        have hset : (Finset.range M).filter
            (fun j => j + 1 ≤ U ω k y ∧ ω.2.1 (y, j) = x) = s := by
          ext j
          rw [Finset.mem_filter]
          constructor
          · rintro ⟨hj, hcond⟩
            by_contra hc
            exact hout j (Finset.mem_sdiff.mpr ⟨hj, hc⟩) hcond
          · intro hj
            exact ⟨hsub hj, hin j hj⟩
        rw [hset]
        exact hcard
    rw [this]
    refine @MeasurableSet.biUnion _ _ (expFiltration d k) _ _ (Finset.countable_toSet _)
      fun s _ => ?_
    refine @MeasurableSet.inter _ (expFiltration d k) _ _ ?_ ?_
    · refine @MeasurableSet.biInter _ _ (expFiltration d k) _ _ (Finset.countable_toSet _)
        fun j _ => ?_
      cases k with
      | zero =>
          have hempty : {ω : Data d | j + 1 ≤ U ω 0 y ∧ ω.2.1 (y, j) = x} = ∅ := by
            ext ω
            simp only [Set.mem_setOf_eq, Set.mem_empty_iff_false, iff_false]
            have : U ω 0 y = 0 := rfl
            omega
          rw [hempty]
          exact @MeasurableSet.empty _ (expFiltration d 0)
      | succ k => exact measurableSet_generator k y x j
    · refine @MeasurableSet.biInter _ _ (expFiltration d k) _ _ (Finset.countable_toSet _)
        fun j _ => ?_
      refine @MeasurableSet.compl _ _ (expFiltration d k) ?_
      cases k with
      | zero =>
          have hempty : {ω : Data d | j + 1 ≤ U ω 0 y ∧ ω.2.1 (y, j) = x} = ∅ := by
            ext ω
            simp only [Set.mem_setOf_eq, Set.mem_empty_iff_false, iff_false]
            have : U ω 0 y = 0 := rfl
            omega
          rw [hempty]
          exact @MeasurableSet.empty _ (expFiltration d 0)
      | succ k => exact measurableSet_generator k y x j
  · intro ω
    unfold LatticeProb.arrivals
    congr 1
    refine Finset.filter_congr fun j hj => ?_
    rw [Finset.mem_range] at hj
    constructor
    · intro h
      exact ⟨by omega, h⟩
    · rintro ⟨-, h⟩
      exact h

/-! ### The field that carries the odometer of the next round -/

/-- The odometer of the closed recursion `eq:parallel`, read off the data after
`k` rounds: `(η + ∑_y I_{y,x}(U_k(y)))⁺`.  It is `G_k`-measurable, and under
the law it is `U_{k+1}`. -/
def expOdometer (d k : ℕ) (ω : Data d) (x : Site d) : ℕ :=
  (max 0 (ω.1 x + ∑ y ∈ nbrFinset x, (arrivals ω.2.1 y x (U ω k y) : ℤ))).toNat

theorem measurable_expOdometer (k : ℕ) (x : Site d) :
    Measurable[expFiltration d k] fun ω : Data d => expOdometer d k ω x := by
  have hsum : Measurable[expFiltration d k] fun ω : Data d =>
      ω.1 x + ∑ y ∈ nbrFinset x, (arrivals ω.2.1 y x (U ω k y) : ℤ) := by
    refine Measurable.add (measurable_eta_expFiltration k x) ?_
    refine Finset.measurable_sum _ fun y _ => ?_
    exact Measurable.fun_comp (fun ⦃_⦄ a => a) (measurable_arrivals_expFiltration k y x)
  exact Measurable.fun_comp (fun ⦃_⦄ a => a) (measurable_const.max hsum)

theorem ae_stack_nbr_law (hd : 1 ≤ d) (ν : Measure ℤ) [IsProbabilityMeasure ν] :
    ∀ᵐ ω ∂(law d ν), ∀ q : Site d × ℕ, ω.2.1 q ∈ nbrFinset q.1 := by
  haveI : IsProbabilityMeasure (LatticeProb.iidLaw d ν) := by
    unfold LatticeProb.iidLaw
    infer_instance
  exact ae_stack_nbr hd (LatticeProb.iidLaw d ν)

/-- `U_{k+1}` agrees almost surely with a `G_k`-measurable field. -/
theorem U_succ_ae_eq_expOdometer (hd : 1 ≤ d) (ν : Measure ℤ) [IsProbabilityMeasure ν]
    (k : ℕ) (x : Site d) :
    (fun ω : Data d => U ω (k + 1) x) =ᵐ[law d ν] fun ω : Data d => expOdometer d k ω x := by
  refine (ae_stack_nbr_law hd ν).mono fun ω hω => ?_
  have hpar := (parallel_of_labelOrder (D := toDriver ω) (labelOrder d) hω).2 k x
  have hcast : (U ω (k + 1) x : ℤ)
      = max 0 (ω.1 x + ∑ y ∈ nbrFinset x, (arrivals ω.2.1 y x (U ω k y) : ℤ)) := hpar
  show U ω (k + 1) x = expOdometer d k ω x
  rw [expOdometer, ← hcast]
  simp

end Parking

end
