/-
The exposure filtration of `lem:exposure`: the initial configuration, and then
one round of instructions at a time.

`expFiltration d k` is the paper's `\mathcal G_k`.  `\mathcal G_0` is generated
by the configuration; for `k ≥ 1`, `\mathcal G_k` is generated by
`\mathcal G_{k-1}` together with the events
`{U_k(y) ≥ j, ρ_j(y) = x}`.  The paper numbers instructions from one and this
formalization from zero, so `ρ_{j+1}(y)` is `ω.2.1 (y, j)` and the event
`{U_k(y) ≥ j+1}` is `j + 1 ≤ U ω k y`.
-/
import Parking.Support.Error

namespace Parking

/-- `\mathcal G_k`, the σ-algebra of the configuration and of the instructions
read in the first `k` rounds. -/
@[implicit_reducible] def expFiltration (d : ℕ) : ℕ → MeasurableSpace (Data d)
  | 0 => MeasurableSpace.comap (fun ω : Data d => ω.1) inferInstance
  | k + 1 => expFiltration d k ⊔ MeasurableSpace.generateFrom
      {A | ∃ (y : Site d) (j : ℕ) (x : Site d),
        A = {ω : Data d | j + 1 ≤ U ω (k + 1) y ∧ ω.2.1 (y, j) = x}}

end Parking
