/-
The filtration that reveals the particles of a finite set of sites one at a time.

Step 2 of `lem:product` (`parking.tex:2367-2394`) fixes the counts, lets `H_i` be
generated by the walks and the uniform variables of the particles `1, …, i` at a
site, and decomposes a conditional covariance along that filtration.  With the
counts held fixed at `a`, the particles at the sites of `N` are the labels below
the count at their site, a FINITE set, and revealing the first `i` of them is the
splicing of the noise along the first `i` labels of that set.  These splicings
are measure preserving, splicing along the first `i` after the first `i+1` is
splicing along the first `i`, the first stage reveals nothing, and the last
stage leaves an observable of the counts and of the particles present at the
sites of `N` unchanged, so the covariance decomposition of
`Support/SpliceAvg.lean` applies to them.
-/
import Parking.Support.NoiseSplice

open MeasureTheory

noncomputable section

namespace Parking

/-- The labels of the particles present at the sites of `N` when the counts are
`a`: at each site of `N`, the labels below its count. -/
def particleLabels {d : ℕ} (N : Finset (Site d)) (a : Site d → ℤ) : Finset (Label d) :=
  N.biUnion fun x => (Finset.range (a x).toNat).image fun i => (x, i)

/-- The first `i` elements of a finite set, in the order of its canonical
enumeration. -/
def prefixSet {α : Type*} (s : Finset α) (i : ℕ) : Set α :=
  {p | ∃ h : p ∈ s, ((s.equivFin ⟨p, h⟩ : Fin s.card) : ℕ) < i}

theorem mem_particleLabels {d : ℕ} {N : Finset (Site d)} {a : Site d → ℤ} {p : Label d} :
    p ∈ particleLabels N a ↔ p.1 ∈ N ∧ p.2 < (a p.1).toNat := by
  simp only [particleLabels, Finset.mem_biUnion, Finset.mem_image, Finset.mem_range]
  constructor
  · rintro ⟨x, hx, i, hi, rfl⟩
    exact ⟨hx, hi⟩
  · rintro ⟨h1, h2⟩
    exact ⟨p.1, h1, p.2, h2, rfl⟩

theorem prefixSet_zero {α : Type*} (s : Finset α) :
    prefixSet s 0 = (∅ : Set α) := by
  ext p
  simp only [prefixSet, Set.mem_setOf_eq, Set.mem_empty_iff_false, iff_false, not_exists]
  exact fun h => Nat.not_lt_zero _

theorem prefixSet_card {α : Type*} (s : Finset α) :
    prefixSet s s.card = (s : Set α) := by
  ext p
  simp only [prefixSet, Set.mem_setOf_eq, Finset.mem_coe]
  constructor
  · rintro ⟨h, -⟩
    exact h
  · intro h
    exact ⟨h, (s.equivFin ⟨p, h⟩).isLt⟩

theorem prefixSet_mono {α : Type*} (s : Finset α) {i j : ℕ} (hij : i ≤ j) :
    prefixSet s i ⊆ prefixSet s j := by
  intro p hp
  obtain ⟨h, hlt⟩ := hp
  exact ⟨h, lt_of_lt_of_le hlt hij⟩

/-- The stage-`i` splicing of the noise: the walks and the uniform variables of
the first `i` particles at the sites of `N` are read from the configuration and
every other label from the independent copy. -/
def particleSplice {d : ℕ} (N : Finset (Site d)) (a : Site d → ℤ) (i : ℕ)
    (b η : PNoise d) : PNoise d :=
  noiseComb (prefixSet (particleLabels N a) i) b η

theorem measurePreserving_particleSplice {d : ℕ} (hd : 1 ≤ d) (N : Finset (Site d))
    (a : Site d → ℤ) (i : ℕ) :
    MeasurePreserving (fun p : PNoise d × PNoise d => particleSplice N a i p.1 p.2)
      ((noiseLaw d).prod (noiseLaw d)) (noiseLaw d) :=
  measurePreserving_noiseComb hd _

theorem particleSplice_idem {d : ℕ} (N : Finset (Site d)) (a : Site d → ℤ) (i : ℕ)
    (b η η' : PNoise d) :
    particleSplice N a i (particleSplice N a i b η) η' = particleSplice N a i b η' :=
  noiseComb_noiseComb (subset_refl _) b η η'

theorem particleSplice_step {d : ℕ} (N : Finset (Site d)) (a : Site d → ℤ) (i : ℕ)
    (b η η' : PNoise d) :
    particleSplice N a i (particleSplice N a (i + 1) b η) η' = particleSplice N a i b η' :=
  noiseComb_noiseComb (prefixSet_mono _ (Nat.le_succ i)) b η η'

theorem particleSplice_zero {d : ℕ} (N : Finset (Site d)) (a : Site d → ℤ)
    (b η : PNoise d) : particleSplice N a 0 b η = η := by
  unfold particleSplice
  rw [prefixSet_zero]
  exact noiseComb_empty b η

/-- Splicing the labels of the sites of `N` back over a splicing of the particles
present there is again a splicing of the same two realizations: it keeps the
dormant labels of the sites of `N` from the independent copy and every other
label from the configuration. -/
theorem noiseComb_particleLabels_comb {d : ℕ} (N : Finset (Site d)) (a : Site d → ℤ)
    (b η : PNoise d) :
    noiseComb {p : Label d | p.1 ∈ N} (noiseComb (particleLabels N a : Set (Label d)) b η) b
      = noiseComb {p : Label d | p.1 ∈ N → p.2 < (a p.1).toNat} b η := by
  classical
  refine Prod.ext ?_ ?_ <;>
    · funext q
      by_cases hN : q.1.1 ∈ N
      · by_cases hc : q.1.2 < (a q.1.1).toNat
        · have hmem : q.1 ∈ (particleLabels N a : Set (Label d)) := by
            simp only [Finset.mem_coe, mem_particleLabels]
            exact ⟨hN, hc⟩
          have hS : q.1 ∈ {p : Label d | p.1 ∈ N → p.2 < (a p.1).toNat} := fun _ => hc
          simp [noiseComb, LatticeProb.comb, Set.mem_setOf_eq, hN]
          rw [if_pos (mem_particleLabels.mpr ⟨hN, hc⟩),
            if_pos (by omega : (q.1.2 : ℤ) < a q.1.1)]
        · have hmem : q.1 ∉ (particleLabels N a : Set (Label d)) := by
            simp only [Finset.mem_coe, mem_particleLabels, not_and]
            exact fun _ => hc
          have hS : q.1 ∉ {p : Label d | p.1 ∈ N → p.2 < (a p.1).toNat} := by
            simp only [Set.mem_setOf_eq, not_forall]
            exact ⟨hN, hc⟩
          simp [noiseComb, LatticeProb.comb, Set.mem_setOf_eq, hN]
          rw [if_neg (fun h => hc (mem_particleLabels.mp h).2),
            if_neg (by omega : ¬ ((q.1.2 : ℤ) < a q.1.1))]
      · have hS : q.1 ∈ {p : Label d | p.1 ∈ N → p.2 < (a p.1).toNat} := fun h => absurd h hN
        have hmem : q.1 ∉ (particleLabels N a : Set (Label d)) := by
          simp only [Finset.mem_coe, mem_particleLabels, not_and]
          exact fun h => absurd h hN
        simp [noiseComb, LatticeProb.comb, Set.mem_setOf_eq, hN]

/-- **The last stage of the filtration.**  An observable of the counts and of the
particles present at the sites of `N` is determined by the walks and the uniform
variables of the particles at those sites, so the splicing that reveals all of
them does not change its value. -/
theorem endpoint_particleSplice {d : ℕ} {N : Finset (Site d)} {F : PData d → ℝ}
    (hFN : Parking.DependsOn N F) (hFP : Parking.ReadsParticles F)
    (a : Site d → ℤ) (b η : PNoise d) (hb : Function.Injective b.2)
    (hs : Function.Injective
      (noiseComb {p : Label d | p.1 ∈ N → p.2 < (a p.1).toNat} b η).2) :
    F (a, noiseComb (particleLabels N a : Set (Label d)) b η) = F (a, b) := by
  classical
  set T : Set (Label d) := (particleLabels N a : Set (Label d)) with hT
  set c : PNoise d := noiseComb T b η with hc
  set c₂ : PNoise d := noiseComb {p : Label d | p.1 ∈ N} c b with hc₂
  have hc₂inj : Function.Injective c₂.2 := by
    rw [hc₂, hc, hT, noiseComb_particleLabels_comb]
    exact hs
  have h1 : F (a, c) = F (a, c₂) := by
    refine hFN _ _ (fun x _ => rfl) ?_ ?_
    · intro q hq
      exact (noiseComb_fst_of_mem (T := {p : Label d | p.1 ∈ N}) hq).symm
    · intro q hq
      exact (noiseComb_snd_of_mem (T := {p : Label d | p.1 ∈ N}) hq).symm
  have h2 : F (a, c₂) = F (a, b) := by
    refine hFP _ _ hc₂inj hb rfl ?_ ?_
    · intro q hq
      by_cases hN : q.1.1 ∈ N
      · have hmem : q.1 ∈ T := by
          rw [hT, Finset.mem_coe, mem_particleLabels]
          exact ⟨hN, hq⟩
        rw [noiseComb_fst_of_mem (T := {p : Label d | p.1 ∈ N}) hN, hc,
          noiseComb_fst_of_mem hmem]
      · exact noiseComb_fst_of_notMem (T := {p : Label d | p.1 ∈ N}) hN
    · intro q hq
      by_cases hN : q.1.1 ∈ N
      · have hmem : q.1 ∈ T := by
          rw [hT, Finset.mem_coe, mem_particleLabels]
          exact ⟨hN, hq⟩
        rw [noiseComb_snd_of_mem (T := {p : Label d | p.1 ∈ N}) hN, hc,
          noiseComb_snd_of_mem hmem]
      · exact noiseComb_snd_of_notMem (T := {p : Label d | p.1 ∈ N}) hN
  rw [h1, h2]

end Parking

end
