import LatticeProb.Prob.Splice

/-!
# The coordinate sub-sigma-algebra and partial integration as conditional expectation

This file builds the sub-sigma-algebra `productCoordAlg b S` of the countable product
space `Π i, X i` generated by the coordinates in `S`, relative to a base point `b` used
to fill in the other coordinates, and shows it is genuinely a sub-sigma-algebra of the
product sigma algebra. It then proves that averaging out the coordinates outside `S` by
`partialInt` computes exactly the conditional expectation onto `productCoordAlg b S`,
which is the main product-measure fact this development is built to supply.
-/

noncomputable section
namespace Parking
open MeasureTheory LatticeProb
variable {ι : Type*} {X : ι → Type*} [∀ i, MeasurableSpace (X i)]

/-- The sigma algebra generated by the coordinates in a set. -/
@[reducible] def productCoordAlg (b : Π i, X i) (S : Set ι) [DecidablePred (· ∈ S)] :
    MeasurableSpace (Π i, X i) :=
  MeasurableSpace.comap (fun ω => comb S ω b) inferInstance

/-- The coordinate truncation `ω ↦ comb S ω b`, which keeps `ω`'s entries on `S` and
replaces the rest by the fixed point `b`, is measurable. -/
theorem measurable_coordTruncate (b : Π i, X i) (S : Set ι) [DecidablePred (· ∈ S)] :
    Measurable (fun ω => comb S ω b) :=
  (measurable_comb S).comp (measurable_id.prodMk measurable_const)

/-- `productCoordAlg b S` is a sub-sigma-algebra of the full product sigma algebra, being
the comap along the measurable truncation map `measurable_coordTruncate`. -/
theorem productCoordAlg_le (b : Π i, X i) (S : Set ι) [DecidablePred (· ∈ S)] :
    productCoordAlg b S ≤ (inferInstance : MeasurableSpace (Π i, X i)) :=
  (measurable_coordTruncate b S).comap_le

omit [∀ i, MeasurableSpace (X i)] in
/-- Truncating `comb S ω η` to `b` outside `S` agrees with truncating `ω` directly to `b`
outside `S`, since both retain only the entries of `ω` on `S`. -/
theorem comb_truncate (b ω η : Π i, X i) (S : Set ι) [DecidablePred (· ∈ S)] :
    comb S (comb S ω η) b = comb S ω b := by
  funext i
  by_cases hi : i ∈ S <;> simp [comb, hi]

/-- Events decided by a coordinate set are unchanged when the other coordinates are resampled. -/
theorem productCoordAlg_mem (b : Π i, X i) (S : Set ι) [DecidablePred (· ∈ S)]
    {A : Set (Π i, X i)} (hA : MeasurableSet[productCoordAlg b S] A) (ω η : Π i, X i) :
    comb S ω η ∈ A ↔ ω ∈ A := by
  obtain ⟨B, _hB, rfl⟩ := hA
  simp only [Set.mem_preimage, comb_truncate]

/-- The partial integral is measurable with respect to the retained coordinates. -/
theorem measurable_partialInt_coord (μ : ∀ i, Measure (X i)) [∀ i, IsProbabilityMeasure (μ i)]
    (b : Π i, X i) (S : Set ι) [DecidablePred (· ∈ S)] {F : (Π i, X i) → ℝ}
    (hF : Measurable F) : Measurable[productCoordAlg b S] (partialInt μ S F) := by
  have he : partialInt μ S F = (partialInt μ S F) ∘ (fun ω => comb S ω b) := by
    funext ω
    exact partialInt_congr μ S F fun i hi => (comb_apply_of_mem hi).symm
  rw [he]
  exact (measurable_partialInt μ S hF).comp (Measurable.of_comap_le le_rfl)

/-- Averaging the omitted independent coordinates is the conditional expectation. -/
theorem partialInt_eq_condExp_coord (μ : ∀ i, Measure (X i)) [∀ i, IsProbabilityMeasure (μ i)]
    (b : Π i, X i) (S : Set ι) [DecidablePred (· ∈ S)] {F : (Π i, X i) → ℝ}
    (hFm : Measurable F) (hFi : Integrable F (Measure.infinitePi μ)) :
    partialInt μ S F =ᵐ[Measure.infinitePi μ]
      (Measure.infinitePi μ)[F | productCoordAlg b S] := by
  let P := Measure.infinitePi μ
  have hle := productCoordAlg_le b S
  have hpi := integrable_partialInt μ S hFi
  apply ae_eq_condExp_of_forall_setIntegral_eq hle hFi (fun _ _ _ => hpi.integrableOn)
  · intro A hA _
    have hAm : MeasurableSet A := hle A hA
    let χ : (Π i, X i) → ℝ := A.indicator (fun _ => 1)
    have hχ (ω η : Π i, X i) : χ (comb S ω η) = χ ω := by
      have hmem := productCoordAlg_mem b S hA ω η
      by_cases hω : ω ∈ A <;> simp [χ, hω, hmem]
    have hmul (f : (Π i, X i) → ℝ) : (fun ω => χ ω * f ω) = A.indicator f := by
      funext ω
      by_cases hω : ω ∈ A <;> simp [χ, hω]
    have hχi : Integrable (fun ω => χ ω * F ω) P := by
      rw [hmul]
      exact hFi.indicator hAm
    have h := integral_mul_partialInt μ S hχ hχi
    rw [hmul, hmul, integral_indicator hAm, integral_indicator hAm] at h
    exact h
  · exact (measurable_partialInt_coord μ b S hFm).stronglyMeasurable.aestronglyMeasurable
end Parking
