/-
Lemma 5.3 of parking.tex, frozen.  `parking.tex:1097-1105` (label
`lem:exposure`):

  "Let $\mathcal G_0\coloneqq\sigma(\eta)$ and, for $k\geq1$, let
   $\mathcal G_k$ be generated by $\mathcal G_{k-1}$ together with the
   indicators $\one\{U_k(y)\geq j,\ \rho_j(y)=x\}$ over all $x$ and $y$ in
   $\Z^d$ and all $j\geq1$.  Then $U_{k+1}$ is measurable with respect to
   $\mathcal G_k$, and conditionally on $\mathcal G_k$ the instructions
   $\rho_j(y)$ with $j>U_k(y)$ are independent with law $P(y,\cdot)$."

`\mathcal G_k` is `expFiltration d k`.  The measurability of `U_{k+1}` is
almost sure rather than pathwise: `U_{k+1}` agrees, off a null set, with a
`\mathcal G_k`-measurable field.  Pathwise it is not `\mathcal G_k`-measurable,
because a realization whose instructions are not neighbours of the site
carrying them can put a particle at a site it is not a candidate for, where it
reads an instruction of index `U_k`, which no generator records; such
realizations are null, and the almost-sure form is what the proof of
`lem:w-martingale` uses.  The conditional independence with the
prescribed conditional law is written as the product rule it is used through:
for every finite family of unread instructions, prescribing a destination for
each one has conditional probability the product of the transition
probabilities, on the event that all of them are still unread.  The paper
numbers instructions from one and this formalization from zero, so
`ρ_{j+1}(y)` is `ω.2.1 (y, j)` and "unread after round `k`" is
`U ω k y ≤ j`.
-/
import Parking.Support.ExposureProduct

open MeasureTheory

-- FROZEN-STATEMENT-BEGIN
theorem Parking.Frozen.exposure (d : ℕ) (hd : 1 ≤ d) (ν : Measure ℤ)
    (hprob : IsProbabilityMeasure ν) :
    (∀ (k : ℕ) (x : Parking.Site d), ∃ g : Parking.Data d → ℕ,
        Measurable[Parking.expFiltration d k] g ∧
          (fun ω : Parking.Data d => Parking.U ω (k + 1) x) =ᵐ[Parking.law d ν] g) ∧
    ∀ (k : ℕ) (s : Finset (Parking.Site d × ℕ)) (f : Parking.Site d × ℕ → Parking.Site d),
      (Parking.law d ν)[fun ω : Parking.Data d => ∏ q ∈ s,
            Set.indicator {ω' : Parking.Data d | Parking.U ω' k q.1 ≤ q.2 ∧ ω'.2.1 q = f q}
              (fun _ => (1 : ℝ)) ω | Parking.expFiltration d k]
        =ᵐ[Parking.law d ν] fun ω : Parking.Data d =>
          (∏ q ∈ s, Set.indicator {ω' : Parking.Data d | Parking.U ω' k q.1 ≤ q.2}
              (fun _ => (1 : ℝ)) ω) * ∏ q ∈ s, Parking.kern d q.1 (f q)
-- FROZEN-STATEMENT-END
:= by
  haveI := hprob
  refine ⟨fun k x => ⟨fun ω => Parking.expOdometer d k ω x,
    Parking.measurable_expOdometer k x, Parking.U_succ_ae_eq_expOdometer hd ν k x⟩, ?_⟩
  intro k s f
  exact Parking.exposure_condExp hd ν k s f
