"""Produce the Lean certificate: a machine-checked record of what is proved.

The certificate is not prose.  Every line of it is generated by running the
checkers and by asking Lean itself for each theorem's axiom closure, so a reader
can reproduce it with the commands it names and compare byte for byte.  The
"consumed by" column of the external-inputs table is computed the same way:
by searching every frozen statement for the external's export name, not by a
hand-maintained list that could go stale.

    python3 tools/certificate.py            # write CERTIFICATE.md
    python3 tools/certificate.py --check    # verify the file on disk is current
"""

from __future__ import annotations

import hashlib
import os
import re
import subprocess
import sys
from datetime import date
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("certificate.py: PyYAML is required (pip install pyyaml)")

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "ledger" / "manifest.yaml"
OUT = ROOT / "CERTIFICATE.md"
ELAN = str(Path.home() / ".elan" / "bin")

# The three axioms of Lean's own logic.  Anything else in a closure -- above all
# `sorryAx` -- means the statement is not proved.
CLASSICAL = {"propext", "Classical.choice", "Quot.sound"}

# The two `External` definitions whose `Prop` has been discharged inside this
# repository rather than left as a bare hypothesis, and the theorem that
# proves it.  There is no fixed naming rule for this (the companion happens
# to be the export with its first letter lower-cased in both cases here), so
# it is recorded once and checked, not inferred.
DISCHARGED = {
    "ext-green-gradient": "Parking.External.greenGradient",
    "ext-stopping": "Parking.External.stopping",
}


def run(cmd: list[str], **kw) -> subprocess.CompletedProcess:
    env = {**os.environ, "PATH": ELAN + ":" + os.environ.get("PATH", "")}
    return subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, env=env, **kw)


def module_names() -> list[str]:
    names = []
    for f in sorted((ROOT / "Parking").rglob("*.lean")):
        names.append(str(f.relative_to(ROOT).with_suffix("")).replace("/", "."))
    return names


def axiom_lines(exports: list[str]) -> dict[str, str]:
    """Ask Lean for each export's axiom closure, in one elaboration.

    Returns the raw comma-separated axiom list Lean reports for each export,
    with no judgment about whether it is clean: a `DRAFT_SORRY` or
    `CONDITIONAL` node's closure legitimately contains `sorryAx`, and it is
    `build()` below, which knows each node's declared state, that decides
    whether a given closure is expected.
    """
    imports = sorted({f"import {m}" for m in module_names()})
    src = "\n".join(imports) + "\n" + "\n".join(f"#print axioms {e}" for e in exports) + "\n"
    probe = ROOT / "scratch" / "_certificate_probe.lean"
    probe.parent.mkdir(exist_ok=True)
    probe.write_text(src, encoding="utf-8")
    try:
        r = run(["lake", "env", "lean", str(probe)], timeout=3600)
    finally:
        probe.unlink(missing_ok=True)
    if r.returncode != 0:
        raise RuntimeError("axiom probe did not elaborate:\n" + r.stdout + r.stderr)
    out: dict[str, str] = {}
    for line in r.stdout.splitlines():
        m = re.match(r"'([^']+)' (?:depends on axioms: \[(.*)\]|does not depend on any axioms)", line)
        if m:
            out[m.group(1)] = m.group(2) or ""
    missing = sorted(set(exports) - out.keys())
    if missing:
        raise RuntimeError("missing axiom closures: " + ", ".join(missing))
    return out


def frozen_hash(node: dict) -> str:
    text = (ROOT / node["file"]).read_text(encoding="utf-8")
    b = text[text.index("-- FROZEN-STATEMENT-BEGIN") + len("-- FROZEN-STATEMENT-BEGIN"):
             text.index("-- FROZEN-STATEMENT-END")]
    if b.startswith("\n"):
        b = b[1:]
    return hashlib.sha256(b.encode("utf-8")).hexdigest()


def frozen_block(node: dict) -> str:
    text = (ROOT / node["file"]).read_text(encoding="utf-8")
    return text[text.index("-- FROZEN-STATEMENT-BEGIN"):text.index("-- FROZEN-STATEMENT-END")]


def used_by(export: str, theorems: list[dict]) -> list[str]:
    """Every theorem node whose frozen statement names this export.

    An `External` enters a theorem only as an explicit hypothesis binder in
    the frozen statement itself, so grepping the frozen block for the
    export's fully qualified name is exact, not a heuristic.
    """
    return [t["id"] for t in theorems if export in frozen_block(t)]


def paper_label(source: str) -> str:
    """The paper anchor: the label when the source names one, else the lines."""
    m = re.search(r"label ([A-Za-z][A-Za-z0-9:_-]*)", source)
    if m:
        return f"`{m.group(1)}`"
    m = re.search(r"\(([A-Za-z][A-Za-z0-9:_-]*)\)", source)
    if m:
        return f"`{m.group(1)}`"
    m = re.search(r"parking\.tex:(\d+)-(\d+)", source)
    if m:
        return f"lines {m.group(1)}-{m.group(2)}"
    m = re.search(r"parking\.tex:(\d+)", source)
    return f"line {m.group(1)}" if m else "—"


def build() -> str:
    manifest = yaml.safe_load(MANIFEST.read_text(encoding="utf-8"))
    nodes = manifest["nodes"]
    theorems = [n for n in nodes if n["kind"] == "theorem"]
    externals = [n for n in nodes if n["kind"] == "definition"]

    r = run(["lake", "build", "Parking"], timeout=7200)
    jobs = re.search(r"Build completed successfully \((\d+) jobs\)", r.stdout)
    if r.returncode != 0:
        raise RuntimeError("certificate: Lean build failed\n" + r.stdout + r.stderr)
    for checker in ("check_manifest.py", "check_constants.py",
                    "check_warnings.py", "sync_docs.py"):
        gate = run([sys.executable, "tools/" + checker], timeout=3600)
        if gate.returncode != 0:
            raise RuntimeError(f"certificate: {checker} failed\n" + gate.stdout + gate.stderr)
    # check_axioms.py is not run as a pass/fail gate here: it exits nonzero
    # whenever any node's closure carries `sorryAx`, which is the normal,
    # expected state of a `DRAFT_SORRY` or `CONDITIONAL` node.  The per-node
    # checks below ask the sharper question this certificate needs -- does
    # every `SEALED` node have a clean closure, and does every clean closure
    # belong to a `SEALED` node -- against the axiom closures fetched directly
    # below, and raise on the first node where the manifest and the closure
    # disagree.
    # check_warnings.py, run above, is the authority on which build warnings
    # are authorized (one `declaration uses 'sorry'` per `DRAFT_SORRY` node);
    # this count is only for the report below.
    warnings = [l for l in r.stdout.splitlines() if l.startswith("warning:")]

    probe_exports = [n["export"] for n in nodes] + list(DISCHARGED.values())
    ax = axiom_lines(probe_exports)

    def extra_axioms(export: str) -> set[str]:
        got = {a.strip() for a in ax[export].split(",") if a.strip()}
        return got - CLASSICAL

    sealed = sum(n["kind"] == "theorem" and n["state"] == "SEALED" for n in nodes)
    open_theorems = [n for n in theorems if n["state"] != "SEALED"]
    draft_theorems = [n for n in open_theorems if n["state"] == "DRAFT_SORRY"]
    conditional_theorems = [n for n in open_theorems if n["state"] == "CONDITIONAL"]
    frozen_only = sum(n["kind"] == "definition" and n["state"] == "FROZEN" for n in nodes)
    toolchain = (ROOT / "lean-toolchain").read_text().strip()
    ml = re.search(r'"rev":\s*"([0-9a-f]{40})"',
                   (ROOT / "lake-manifest.json").read_text(encoding="utf-8"))
    paper = ROOT / "paper" / "parking.tex"
    paper_sha = hashlib.sha256(paper.read_bytes()).hexdigest()

    lines: list[str] = []
    A = lines.append
    A("# Lean certificate")
    A("")
    A("*Sharpness and critical scaling of parking*, Bou-Rabee and Panagiotis,")
    A("arXiv:2609.02820.  This file records what a machine has checked, and how")
    A("to check it again.  It is generated by `python3 tools/certificate.py`; do")
    A("not edit it by hand.")
    A("")
    A("## What is claimed")
    A("")
    A("The paper's registered statements are proved in Lean 4 from Mathlib and the")
    A("shared library `LatticeProb`, under the hypotheses displayed in their frozen")
    A("declarations, with no added axiom and no `sorry`, for every node in state")
    A("`SEALED` below.  Cited inputs are proposition-valued predicates in")
    A("`Parking/External/`, carried as explicit hypotheses together with each")
    A("theorem's own hypotheses; two of them have themselves been proved, inside")
    A("this repository, rather than left as bare hypotheses, and are marked")
    A("accordingly.  `CORRESPONDENCE.md` records the correspondence with the paper")
    A("and `PROOF.md` describes the proof and the Lean tree.")
    A("")
    if open_theorems:
        A(f"{len(open_theorems)} theorem nodes are not yet proved: {len(draft_theorems)}")
        A(f"carry a `sorry` of their own and {len(conditional_theorems)} apply one of")
        A("those, so every one of them shows `sorryAx` in the axiom closure below,")
        A("and this is disclosed rather than a defect.  `PROOF.md` marks them open")
        A("in the Lean tree.")
        A("")
    A("## Environment")
    A("")
    A("| | |")
    A("|---|---|")
    A(f"| Lean toolchain | `{toolchain}` |")
    A(f"| Mathlib revision | `{ml.group(1) if ml else 'unknown'}` |")
    A(f"| Paper (`paper/parking.tex`) SHA-256 | `{paper_sha}` |")
    A(f"| Build | succeeded{f', {jobs.group(1)} jobs' if jobs else ''} |")
    A(f"| Build warnings | {len(warnings)} |")
    A(f"| Generated | {date.today().isoformat()} |")
    A("")
    A("## Reproducing it")
    A("")
    A("```")
    A("elan toolchain install $(cat lean-toolchain)")
    A("lake build Parking")
    A("python3 tools/check_manifest.py     # frozen statements match their hashes")
    A("python3 tools/check_axioms.py       # sorryAx appears only where the state says so")
    A("python3 tools/check_warnings.py     # the build emits no unauthorized warning")
    A("python3 tools/check_constants.py    # parameter order for uniform constants")
    A("python3 tools/sync_docs.py --write  # generate the manifest-derived tables")
    A("python3 tools/certificate.py --check")
    A("```")
    A("")
    A("## The theorems, and what each depends on")
    A("")
    A("`#print axioms` reports the full transitive axiom closure of a proof.  A")
    A("closure of exactly `propext, Classical.choice, Quot.sound` is classical")
    A("mathematics and nothing more; those three are Lean's own, not ours.  A")
    A("closure containing `sorryAx` means the statement is not proved; below, that")
    A("is expected exactly at the two nodes whose state is not `SEALED`.")
    A("")
    A("| # | node | Lean name | state | paper | axiom closure |")
    A("|---|---|---|---|---|---|")
    clean = 0
    for i, n in enumerate(nodes, 1):
        e = n["export"]
        extra = extra_axioms(e)
        if n["kind"] == "definition":
            if n["id"] in DISCHARGED:
                comp = DISCHARGED[n["id"]]
                comp_extra = extra_axioms(comp)
                if comp_extra:
                    raise RuntimeError(
                        f"{n['id']}: companion `{comp}` is not axiom-clean: {sorted(comp_extra)}")
                verdict = f"proved (companion `{comp}`, classical only)"
            else:
                verdict = "assumed (a cited theorem, stated as a proposition)"
        elif not extra:
            if n["state"] != "SEALED":
                raise RuntimeError(
                    f"{n['id']}: axiom closure is clean but manifest state is {n['state']}")
            verdict = "classical only"
            clean += 1
        else:
            if n["state"] == "SEALED":
                raise RuntimeError(
                    f"{n['id']}: manifest state is SEALED but axiom closure carries {sorted(extra)}")
            verdict = "**" + ", ".join(sorted(extra)) + "**"
        A(f"| {i} | `{n['id']}` | `{e}` | `{n['state']}` | {paper_label(n['source'])} | {verdict} |")
    A("")
    A(f"All {clean} theorem declarations with a clean closure have axiom closures")
    A(f"contained in the three classical axioms; the {sealed} theorem nodes in state")
    A(f"`SEALED` are exactly these.  {len(open_theorems)} theorem node(s) are not yet")
    A(f"sealed and carry `sorryAx` as shown.  The {frozen_only} external definitions in")
    A("state `FROZEN` are not proved here and supply no closure of their own; the")
    A(f"{len(DISCHARGED)} in state `SEALED` are proved by the companion theorem named")
    A("above. A clean closure for a `definition` node's own export reports only")
    A("that stating the proposition needed no axiom, not that the proposition is")
    A("true; only the companion closure does that.")
    A("")
    A("## External inputs")
    A("")
    A("Each external predicate is a cited theorem of the literature, stated in the")
    A("paper's vocabulary and carried as an explicit hypothesis.  The \"consumed by\"")
    A("column lists every frozen statement whose hypotheses name this export,")
    A("found by searching the frozen text itself, not by a maintained list.")
    A("")
    A("| node | Lean name | state | consumed by |")
    A("|---|---|---|---|")
    for n in externals:
        sites = used_by(n["export"], theorems)
        cell = ", ".join(f"`{s}`" for s in sites) if sites else "—"
        A(f"| `{n['id']}` | `{n['export']}` | `{n['state']}` | {cell} |")
    A("")
    A("## Frozen statements")
    A("")
    A("The bytes of each statement are pinned, so a statement cannot be weakened")
    A("after the fact without the hash changing.  `tools/check_manifest.py`")
    A("verifies these; the recipe is in `CORRESPONDENCE.md`.")
    A("")
    A("| node | SHA-256 of the frozen statement |")
    A("|---|---|")
    for n in nodes:
        h = frozen_hash(n)
        flag = "" if h == n["frozen_sha256"] else "  ← MISMATCH"
        A(f"| `{n['id']}` | `{h}`{flag} |")
    A("")
    A("## What is not claimed")
    A("")
    A("- The cited theorems in `Parking/External/` (the rows marked *assumed*")
    A("  above) are not proved here; each statement that uses one carries it as an")
    A("  explicit hypothesis. Two of the twelve have been discharged by a proof in")
    A("  this repository or the shared library, and are marked *proved* instead.")
    A("- `prop-spatial-scaling` and `prop-oriented-scaling` are `DRAFT_SORRY`:")
    A("  their statement is frozen and registered, and no proof exists yet.")
    A("  `thm-oriented-walk` and `thm-nearest` are `CONDITIONAL`: their own proof")
    A("  carries no `sorry`, but it applies one of those two draft nodes, so their")
    A("  axiom closure carries `sorryAx` until that node is sealed.")
    A("- The proof ideas and the related work of the paper's introduction are")
    A("  outside the formalization.")
    A("")
    return "\n".join(lines) + "\n"


def main() -> int:
    try:
        text = build()
    except (RuntimeError, subprocess.TimeoutExpired) as error:
        print(f"certificate: {error}", file=sys.stderr)
        return 1
    if "--check" in sys.argv[1:]:
        if not OUT.exists():
            print("certificate: CERTIFICATE.md is missing", file=sys.stderr)
            return 1
        cur = OUT.read_text(encoding="utf-8")
        strip = lambda s: re.sub(r"\| Generated \| .* \|", "", s)
        if strip(cur) != strip(text):
            print("certificate: CERTIFICATE.md is out of date; regenerate it",
                  file=sys.stderr)
            return 1
        print("certificate: OK (CERTIFICATE.md matches the checked state)")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"certificate: wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
